### ISSUE TITLE
fit_generator issue

### ISSUE THREAD

**Issue by nikogamulin** [tensorflow/neural-structured-learning#15]
Hi, I tried to modify the logic according to [this suggestion](https://github.com/tensorflow/neural-structured-learning/issues/3) but haven't managed to run training procedure successfully.

**Here is the code:**

```
import os
os.environ['TF_KERAS'] = '1'

import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint, Callback
import dataloader
from heatmaps import *
import numpy as np
from keras_radam import RAdam
import neural_structured_learning as nsl


image_size = 200
## output shape is the same as input
n = 32 * 5
nClasses = 6
nfmp_block1 = 64
nfmp_block2 = 128
batch_size = 64

IMAGE_ORDERING = "channels_last"

model = tf.keras.Sequential([
    tf.keras.Input(shape=(image_size, image_size, 3)),
    # Encoder Block 1
    Conv2D(nfmp_block1, (3, 3), activation='relu', padding='same', name='block1_conv1', data_format=IMAGE_ORDERING),
    Conv2D(nfmp_block1, (3, 3), activation='relu', padding='same', name='block1_conv2', data_format=IMAGE_ORDERING),
    MaxPooling2D((2, 2), strides=(2, 2), name='block1_pool', data_format=IMAGE_ORDERING),
    # Encoder Block 2
    Conv2D(nfmp_block2, (3, 3), activation='relu', padding='same', name='block2_conv1', data_format=IMAGE_ORDERING),
    Conv2D(nfmp_block2, (3, 3), activation='relu', padding='same', name='block2_conv2', data_format=IMAGE_ORDERING),
    MaxPooling2D((2, 2), strides=(2, 2), name='block2_pool', data_format=IMAGE_ORDERING),
    ## bottoleneck
    (Conv2D(n, (int(image_size / 4), int(image_size / 4)),
                activation='relu', padding='same', name="bottleneck_1", data_format=IMAGE_ORDERING)),
    (Conv2D(n, (1, 1), activation='relu', padding='same', name="bottleneck_2", data_format=IMAGE_ORDERING)),
    ## Decoder Block
    ## upsampling to bring the feature map size to be the same as the input image i.e., heatmap size
    Conv2DTranspose(nClasses, kernel_size=(4, 4), strides=(4, 4), use_bias=False, name='upsample_2',
                             data_format=IMAGE_ORDERING),
    ## Reshaping is necessary to use sample_weight_mode="temporal" which assumes 3 dimensional output shape
    ## See below for the discussion of weights
    Reshape((image_size * image_size * nClasses, 1))
])

# Wrap the model with adversarial regularization.
adv_config = nsl.configs.make_adv_reg_config(multiplier=0.2, adv_step_size=0.05)
adv_model = nsl.keras.AdversarialRegularization(model, adv_config=adv_config)

radam = RAdam(total_steps=10000, warmup_proportion=0.1, min_lr=1e-5)
adv_model.compile(optimizer=radam, loss='mse', sample_weight_mode="temporal")

data_folder = 'data'
id2filename, filename2id, annotated_images = dataloader.get_image_annotations(data_folder)
df = dataloader.get_annotation_dataframe(id2filename, annotated_images)
msk = np.random.rand(len(df)) < 0.8
train = df[msk]
test = df[~msk]
encoding = MultiPointHeatmapEncoding(image_size, df, batch_size=64)

model_name = 'stacked_hourglass_adv'
log_dir = "logs/{}".format(model_name)
model_filename = "saved-models/{}.h5".format(model_name)

train_gen = encoding.generator(train, batch_size)
test_gen = encoding.generator(test, batch_size, get_weights=True)

steps_per_epoch = len(train) // batch_size
validation_steps = len(test) // batch_size
if validation_steps == 0:
    validation_steps = 1
if steps_per_epoch == 0:
    steps_per_epoch = 1

cb_tensorboard = TensorBoard(log_dir=log_dir, histogram_freq=1, write_graph=True, write_images=False)
callback_save_images = CallbackHeatmapOutput(model, get_generator(test_gen), log_dir, encoding)
checkpoint = ModelCheckpoint(model_filename, monitor='val_loss', verbose=1, save_best_only=True, mode='min')


history = adv_model.fit_generator(
            get_generator_dict(train_gen),
            validation_data=get_generator_dict(test_gen),
            steps_per_epoch=steps_per_epoch,
            epochs=5000,
            validation_steps=validation_steps,
            verbose=2,
            use_multiprocessing=True,
            callbacks=[checkpoint, callback_save_images, cb_tensorboard]
        )
```

before trying to use Neural Structured Learning, I used get_generator; the code is the following:
```
def get_generator(in_gen, should_augment=True):
    if should_augment:
        image_gen = ImageDataGenerator(fill_mode='reflect',
                                       data_format='channels_last',
                                       brightness_range=[0.5, 1.5])
    else:
        image_gen = ImageDataGenerator(fill_mode='reflect',
                                       data_format='channels_last',
                                       brightness_range=[1, 1])
    for items in in_gen:
        if len(items) == 2:
            in_x, in_y = items
        else:
            in_x, in_y, weights = items
        g_x = image_gen.flow(255 * in_x, in_y, batch_size=in_x.shape[0])
        x, y = next(g_x)
        yield x / 255.0, y
```

Then, according to suggestion, I modified the above generator to output the dictionary:
```
def get_generator_dict(in_gen, should_augment=True):
    if should_augment:
        image_gen = ImageDataGenerator(fill_mode='reflect',
                                       data_format='channels_last',
                                       brightness_range=[0.5, 1.5])
    else:
        image_gen = ImageDataGenerator(fill_mode='reflect',
                                       data_format='channels_last',
                                       brightness_range=[1, 1])
    for items in in_gen:
        if len(items) == 2:
            in_x, in_y = items
        else:
            in_x, in_y, weights = items
        g_x = image_gen.flow(255 * in_x, in_y, batch_size=in_x.shape[0])
        x, y = next(g_x)

        yield {'feature': x / 255.0, 'label': y}
```

**Nevertheless, I get the following error:**

> Traceback (most recent call last):
>   File "/home/niko/programs/pycharm-community-2019.2.1/helpers/pydev/pydevd.py", line 2060, in <module>
>     main()
>   File "/home/niko/programs/pycharm-community-2019.2.1/helpers/pydev/pydevd.py", line 2054, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "/home/niko/programs/pycharm-community-2019.2.1/helpers/pydev/pydevd.py", line 1405, in run
>     return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
>   File "/home/niko/programs/pycharm-community-2019.2.1/helpers/pydev/pydevd.py", line 1412, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/niko/programs/pycharm-community-2019.2.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/home/niko/workspace/pupil-detection-v2/fcn-adv.py", line 92, in <module>
>     callbacks=[checkpoint, callback_save_images, cb_tensorboard]
>   File "/home/niko/workspace/advanced-computer-vision-course/venv_python3/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
>     steps_name='steps_per_epoch')
>   File "/home/niko/workspace/advanced-computer-vision-course/venv_python3/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 209, in model_iteration
>     callbacks.on_epoch_begin(epoch, epoch_logs)
>   File "/home/niko/workspace/advanced-computer-vision-course/venv_python3/lib/python3.5/site-packages/tensorflow_core/python/keras/callbacks.py", line 283, in on_epoch_begin
>     callback.on_epoch_begin(epoch, logs)
>   File "/home/niko/workspace/advanced-computer-vision-course/venv_python3/lib/python3.5/site-packages/tensorflow_core/python/keras/callbacks_v1.py", line 382, in on_epoch_begin
>     self.model._make_test_function()
>   File "/home/niko/workspace/advanced-computer-vision-course/venv_python3/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 2145, in _make_test_function
>     self._feed_targets +
> AttributeError: 'AdversarialRegularization' object has no attribute '_feed_inputs'

**Comment by csferng** [comment]
@nikogamulin, thanks for the question.

The `TensorBoard` callback object in TensorFlow 1.x doesn't work with subclassed models, and unfortunately `AdversarialRegularization` is one. Could you please try the code in TensorFlow 2.0?

**Comment by nikogamulin** [comment]
Thanks, @csferng! I have migrated to TF 2.0 and everything works fine now.
